// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisteruserTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void registeruser() {
        driver.get("https://www.opencart.com/");
        driver.manage().window().setSize(new Dimension(1376, 744));
        driver.findElement(By.cssSelector(".btn-xl:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".btn-black")).click();
        driver.findElement(By.id("input-username")).click();
        driver.findElement(By.id("input-username")).sendKeys("katrina.123");
        driver.findElement(By.id("input-firstname")).click();
        driver.findElement(By.id("input-firstname")).sendKeys("Katrīna");
        driver.findElement(By.id("input-lastname")).click();
        driver.findElement(By.id("input-lastname")).sendKeys("Apfelbauma");
        driver.findElement(By.id("input-email")).click();
        driver.findElement(By.id("input-email")).sendKeys("katrina.apfelbauma@gmail.com");
        driver.findElement(By.id("input-country")).click();
        {
            WebElement dropdown = driver.findElement(By.id("input-country"));
            dropdown.findElement(By.xpath("//option[. = 'Latvia']")).click();
        }
        driver.findElement(By.id("input-country")).click();
        driver.findElement(By.id("input-password")).click();
        driver.findElement(By.id("input-password")).sendKeys("sda1234");
    }
}
